name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v3

    - name: Install Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Clone GitLab Repository
      env:
        GITLAB_USER: ${{ secrets.GITLAB_USER }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
      run: |
        git clone https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.com/anima-regem/ieee-sb-gec-palakkad.git
        cd ieee-sb-gec-palakkad
        git remote set-url origin https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.com/anima-regem/ieee-sb-gec-palakkad.git

    - name: Sync GitHub Repository to GitLab Repository
      env:
        GITLAB_USER: ${{ secrets.GITLAB_USER }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
      run: |
        git clone https://github.com/IEEE-SB-GEC-Palakkad/ieee-sb-website.git
        cd ieee-sb-website
        git remote add gitlab https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.com/anima-regem/ieee-sb-gec-palakkad.git
        git push gitlab main:stable --force
